# Generated by Django 2.2.1 on 2019-06-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190612_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
